### ISSUE TITLE
Example "Command Chaining" doesn't work

### ISSUE THREAD

**Issue by dvp2015** [BrianPugh/cyclopts#213]
The example ["Command Chaining"](https://cyclopts.readthedocs.io/en/latest/command_chaining.html) in the online documentation doesn't work:

```
╭─ Error ──────────────────────────────────────────────────────────────────────╮
│ Unknown option: "--flag".                                                    │
╰──────────────────────────────────────────────────────────────────────────────╯

Process finished with exit code 1
```
The execution fails on argument parsing and doesn't reach 'main' function.
Using `main()` directly
```
    # app.meta(["foo", "123", "AND", "foo", "456", "AND", "bar", "--flag"])
    main("foo", "123", "AND", "foo", "456", "AND", "bar", "--flag")
```
produces the expected result. 
But it looks like "app.meta()" is to be used in that case.

**Comment by BrianPugh** [comment]
Seems like those docs were a little stale; I updated them in #214 and they should work now. Thanks for opening this issue!
