### ISSUE TITLE
[Feature Request] Dataclasses as commands

### ISSUE THREAD

**Issue by dominikandreas** [BrianPugh/cyclopts#228]
Given some existing config dataclass, I would like to parse arguments to create the config. 

Example:

```python

import sys

from cyclopts import App

@dataclass
class MyConfig:
    a: int = 1
    b: int = 2

config = object.__new__(MyConfig)

app = App()
app.default(config.__init__)

sys.argv = [__file__,  "--a", "3", "--b", "4"]
app()
print(config)
```
`MyConfig(a=3, b=4)`

This already works as is, but I was wondering if a prettier solution already exists, either currently working or planned for version 3? 

Generally, I would prefer defining a CLI around dataclasses rather than function implementations (one reason being that it's easier to extend something based on classes using inheritance).

I assume someone else has already thought about this, so before I start reinventing the wheel, I thought I should ask here.

Thanks for the great work, really like it so far  👍

**Comment by BrianPugh** [comment]
ok, the positional arguments should now work on `dev-3.0.0`. The example provided above now fully works as expected.

**Comment by BrianPugh** [comment]
v3.0.0 has been released! Please let me know if you run into any issues, thanks!
