### ISSUE TITLE
feature: list options before list arguments

### ISSUE THREAD

**Issue by thvitt** [BrianPugh/cyclopts#239]
I really like the project and its support for modern type annotations, however, there is one thing I was not yet able to solve.

I am trying to implement a command line interface that has both repeatable arguments and options, i.e. something like this:

```sh
cmd --ext .pdf --ext .html foo.md bar.md
```

With argparse, this can be achieved using action="append":

```python
>>> parser = argparse.ArgumentParser()
>>> parser.add_argument("files", nargs="+", type=Path)
>>> parser.add_argument("--ext", action="append")
>>> args = parser.parse_args()
Namespace(files=[PosixPath('foo.md'), PosixPath('bar.md')], ext=['.pdf', '.html'])
```

With typer, this is the outcome of:
```python
@app.command()
def rules(files: list[Path], ext: list[str] = []):
    print(files)
    print(ext)
```

With cyclopts, I was not able to achieve this. With the attempt:
```python
@app.default
def rules(files: list[Path], ext: list[str] = []):
    print(files)
    print(ext)
```
`--ext` gobbles all following arguments and the only way to call this command without cyclopts complaining about missing files is to move the options to the end of the command line: `cmd foo.md bar.md --ext .pdf .html` (or `cmd foo.md bar.md --ext .pdf .html`). This does not feel natural, though; most command line interfaces I know have their file arguments last. Also, the common `--` argument to delimit options from arguments in ambiguous cases does not seem to be supported (which would allow for `cmd --ext .pdf .html -- foo.md bar.md`)

**Comment by BrianPugh** [comment]
>  This does not feel natural

I completely agree. Luckily right now I'm polishing up the v3.0.0 release and we can fix this behavior! For handling repeatable arguments, how about we change the parsing logic such that when the parameter is `KEYWORD_ONLY`, it will only consume one "element" worth of CLI tokens.

The command would then be
```python
@app.command()
def rules(files: list[Path], *, ext: list[str] = []):
    print(files)
    print(ext)
```

And the CLI parsing would be more in-line with what you expect.

>  Also, the common -- argument to delimit options from arguments in ambiguous cases does not seem to be supported.

I think we can add support for this as well. This would just be searching for `--` in the input token stream, and forcing anything that comes after to be parsed as positional arguments, correct?

**Comment by thvitt** [comment]
> I completely agree. Luckily right now I'm polishing up the v3.0.0 release and we can fix this behavior! For handling repeatable arguments, how about we change the parsing logic such that when the parameter is `KEYWORD_ONLY`, it will only consume one "element" worth of CLI tokens.

That sounds good! I assume that still allows for multiple tokens when the number of required tokens is known, e.g., for the Coordinates in your draw.py test case one element would boil down to two tokens

> I think we can add support for this as well. This would just be searching for `--` in the input token stream, and forcing anything that comes after to be parsed as positional arguments, correct?

Yes, even if the arguments after `--` start with `-`. See, e.g., rm(1), for which `rm -- -foo` would delete a file named `-foo` instead of reading the `-f` as `--force`.

**Comment by BrianPugh** [comment]
This should now work as expected on the `dev-3.0.0` branch. I think it should be released sometime within the next 2 or 3 weeks; things have been hectic and writing up documentation has been taking up way more time than I was expecting.

**Comment by thvitt** [comment]
I have been able to test it now, and it works quite wonderful. Thanks for implementing this!

**Comment by BrianPugh** [comment]
v3.0.0 has been released! If you have any issues with the features, please let me know! Thanks!
