### ISSUE TITLE
Feature request: counting flags

### ISSUE THREAD

**Issue by vhdirk** [BrianPugh/cyclopts#249]
I've seen a lot of cli's where verbosity can be controlled by repeating a `-v` flag. So either `-v -v -v` or `-vvv` (though the latter seems less common).

I've been trying to emulate this using a converter but since the verbosity is defined as an `int`, the `-v` parameter seems to always expect a value. 

A cherry on top would be the case where a single occurance of `-v` could optionally accept a value so the 2 options would be possible at the same time

**Comment by BrianPugh** [comment]
I was hoping that something like the following would "just work":

```python
from cyclopts import App, Parameter
from typing import Annotated

app = App()


@app.default
def main(
    *,
    verbose: Annotated[tuple[bool, ...], Parameter(name=("--verbose", "-v"))] = (),
):
    verbosity = sum(verbose)
    print(f"{verbosity=}")


if __name__ == "__main__":
    app()
```

However, it does not (and I consider that a bug on my part). So I'll try and fix this ASAP. Assuming that the above situation worked as intended, would that satisfy your need?

**Comment by vhdirk** [comment]
Cool, thanks!

I was trying to do something like argparse:

```python
>>> parser = argparse.ArgumentParser()
>>> parser.add_argument('--verbose', '-v', action='count', default=0)
>>> parser.parse_args(['-vvv'])
Namespace(verbose=3)
```

Could `Parameter` also take an 'action' like that? perhaps in the form of a functor?

**Comment by vhdirk** [comment]
Cool ! Thanks a lot! 🙏
