### ISSUE TITLE
Feature request: let enum types accept values

### ISSUE THREAD

**Issue by vhdirk** [BrianPugh/cyclopts#250]
In my applications, I have a habit of defining enums like:

```python
class MyEnum(str, Enum):
    GENERAL = "general"
    SOMETHING = "some"
    LONG_OPTION_THING = "long"
```

or 

```python

class VerbosityLevel(int, Enum):
    SILENT = 0
    DEBUG = 1
    INFO = 2
    WARNING = 3
    ERROR = 4
    CRITICAL = 5
```

One might argue that for strings specifically, I could just use the `Literal` type hint. But enums make refactoring easier in my IDE.

Currently, Cyclopts will transform the variant names to kebab-case. I think it'd be nice if to be able to pass the variant value rather than the name. Or perhaps allow both? In order for that to behave properly, variant values should be unique. IMO that could be left as an exercise to the user if this setting where optional.

**Comment by BrianPugh** [comment]
It's not a 100% satisfactory solution, but the following would allow you to supply either the name or the value:

```python
from cyclopts import App, Parameter
from typing import Annotated
from enum import Enum

app = App()

class VerbosityLevel(int, Enum):
    SILENT = 0
    DEBUG = 1
    INFO = 2
    WARNING = 3
    ERROR = 4
    CRITICAL = 5

def _enum_converter(type_, tokens):
    assert len(tokens) == 1
    value = tokens[0].value
    try:
        return type_[value]
    except KeyError:
        return type_(int(value))

@app.default
def main(
    *,
    verbose: Annotated[VerbosityLevel, Parameter(converter=_enum_converter)],
):
    print(f"{verbose=}")

if __name__ == "__main__":
    app()
```

```bash
$ python issue-250.py --verbose ERROR
verbose=<VerbosityLevel.ERROR: 4>
$ python issue-250.py --verbose 4
verbose=<VerbosityLevel.ERROR: 4>

```

Unfortunately, on the help screen, only the enum keys choices would be displayed:
```
Usage: main COMMAND [OPTIONS]

╭─ Commands ─────────────────────────────────────────────────────────────────────────────────╮
│ --help -h  Display this message and exit.                                                  │
│ --version  Display application version.                                                    │
╰────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Parameters ───────────────────────────────────────────────────────────────────────────────╮
│ *  --verbose  [choices: silent, debug, info, warning, error, critical] [required]          │
╰────────────────────────────────────────────────────────────────────────────────────────────╯
```

I'm hesitant to explicitly add a feature for this in Cyclopts, because I believe that the **value** of an enum should be 100% abstracted away from the user. Having the user specify `4` instead of `ERROR` has that abstraction leaking.

**Comment by vhdirk** [comment]
Thanks!

I should've mentioned; that's what I have now:

```python
def enum_converter(enum_type):
    def enum_converter(type_, tokens: Sequence[Token]) -> int:
        value = tokens[0].value

        try:
            return type_(enum_type(int(value, 10)).value)
        except ValueError:
            return type_(enum_type[value]).value

    return enum_converter


@dataclass(kw_only=True)
class Tool:
    verbose: Annotated[
        int,
        Parameter(
            name=["--verbose", "-v"],
            help=f"Verbosity level [choices: { ', '.join([f'{lv.name.lower()}: {lv.value}' for lv in list(VerbosityLevel)]) }]",
            converter=enum_converter(VerbosityLevel),
        ),
    ] = 0
```

Yet for me, these choices weren't automatically displayed? I would've been content with allowing numeric params but not displaying those choices. But when adding that converter, the choices help text wasn't shown at all

**Comment by BrianPugh** [comment]
Do we think this is a satisfactory-enough answer? At the moment I don't see strong enough evidence for additional features in Cyclopts for this use-case.

**Comment by vhdirk** [comment]
I think I could actually work around this by using `Verbosity | Literal[0] | Literal[1] | ...` here. 

Or, a possibility to rename an enum variant would also be cool?

**Comment by BrianPugh** [comment]
I'm going to close this for now, because I don't think there's any actionable items. If we can come up with a non-clunky user-facing way of handling more enum configuration, we can re-open.
