### ISSUE TITLE
Feature request: Setting help panel order of commands

### ISSUE THREAD

**Issue by beskep** [BrianPugh/cyclopts#257]
I often use cyclopts to create scripts for my research, and sometimes I want the commands to be executed in an order.

For example, I might want to parse data files, EDA, and detect outliers in that order. But the help panel would be displayed in the following order

```
╭─ Commands ──────────────────────────────────────────────╮
│ detect-outlier                                          │
│ eda                                                     │
│ parse-data                                              │
│ --help -h       Display this message and exit.          │
│ --version       Display application version.            │
╰─────────────────────────────────────────────────────────╯
```

This is quite confusing when using the script later.

How about the option to display commands in the order of registration, not than sorting by name?
Or letting the user manually decide the order.

Thanks for reading and thanks for the great package!

**Comment by BrianPugh** [comment]
Hi beskep!

A related feature is that Cyclopts [supports user-defined ordering of Groups](https://cyclopts.readthedocs.io/en/latest/groups.html#help-page). You could add each command to their own group and have them ordered that way, but it's not exactly what you asked for.

We could add a similar `sort_key` to `App.command`; I think that wouldn't be too much trouble and it would be consistent with the Group feature. Displaying commands in order of registration could then be expressed as:

```python
"""Example of forcing registration-order."""
import itertools
from cyclopts import App

_counter = itertools.count()
app = App()

@app.command(sort_key=next(_counter))
def foo():
    pass

@app.command(sort_key=next(_counter))
def bar():
    pass
```

What do you think of this?

**Comment by beskep** [comment]
I knew about group ordering, but I couldn't use it for commands because I already group my commands for preprocessing, analysing, plotting, etc.
I was using App inherited class `if help_panel.format == "command": help_panel.sort()` is removed.

A `sort_key` option would be nice! It would be a simple solution.
Thanks you for the answer.

**Comment by BrianPugh** [comment]
sounds like a plan; i can implement this soon!

**Comment by beskep** [comment]
That was quick! Thank you very much.
