### ISSUE TITLE
Path validator gives misleading error message

### ISSUE THREAD

**Issue by Ravencentric** [BrianPugh/cyclopts#65]
take this for an example
```py
# Must exist, must be a file, must NOT be a directory
validator=validators.Path(exists=True, file_okay=True, dir_okay=False)
```
```txt
> python -m test --config "D:\this_dir_exists"
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Invalid value for --config. D:\this_dir_exists is not a directory.                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```
This is wrong, It is a directory, it's not supposed to be a directory but it is one. same with `file_okay=False`

The message should be something like `Invalid value for --config. Only file input is allowed but D:\this_dir_exists is a directory.`

**Comment by BrianPugh** [comment]
Thanks for the report! To confirm, the solution is just to remove the "not" from the error message, correct? This one melted my brain because it has like 3 negations 😄 .

If so, this will be fixed in develop-v2 (eta still by EOD sunday).

**Comment by Ravencentric** [comment]
> the solution is just to remove the "not"
Yep! Currently it says the exact opposite of what it should

**Comment by BrianPugh** [comment]
will close this issue once v2 is released. I'll let this sit for another day in case you discover any behavior/bugs you don't like.

I'll also try and add some more tests for any lines that currently don't have coverage.

**Comment by Ravencentric** [comment]
I have been thinking about this and I personally don't find `exist=False` a good default. I feel like if I'm going to use the validator without any explicit arguments like,`validator=validators.Path()`, then I'm expecting it to atleast check it's an existing path on the system.

**Comment by BrianPugh** [comment]
hm, good to have this discussion now in-case we want to make a breaking change.

1. I agree, I think `validators.Path(exist=True)` is the typical use, and so for that reason would make a better default.

2. The current default behavior is "least restrictive", and can be configured to be more restrictive.

3. The `click` (and, by extension, Typer) [default is `exist=False`](https://click.palletsprojects.com/en/7.x/parameters/#parameter-types). Not that this is justification alone, but should be additionally considered.

For reason (1), I want to change it. For reason (2), I want to keep it as-is.

**Comment by BrianPugh** [comment]
An additional option, not-mutually-exclusive-option: I introduce a new submodule `cyclopts.types` that just has a bunch of annotated common types.

So for this use-case:

```
ExistingPath = Annotated[Path, Parameter(validator=validators.Path(exists=True))]
ExistingFile = Annotated[Path, Parameter(validator=validators.Path(exists=True, dir_okay=False))]
ExistingDirectory = Annotated[Path, Parameter(validator=validators.Path(exists=True, file_okay=False))]
```

And then the user can just annotated:

```
def foo(my-dir: ExistingDirectory):
    pass
```

Downside: The actual type is less obvious to someone new to your codebase.

**Comment by Ravencentric** [comment]
That actually sounds like a great idea. Sort of similar to Pydantic validation types (so it's already something python users are familiar with)

> Downside: The actual type is less obvious to someone new to your codebase.

I don't think this will be too much of an issue, since the types come from cyclopts and will be documented.

+1 on this module

**Comment by Ravencentric** [comment]
> hm, good to have this discussion now in-case we want to make a breaking change.
> 
> 1. I agree, I think `validators.Path(exist=True)` is the typical use, and so for that reason would make a better default.
> 2. The current default behavior is "least restrictive", and can be configured to be more restrictive.
> 3. The `click` (and, by extension, Typer) [default is `exist=False`](https://click.palletsprojects.com/en/7.x/parameters/#parameter-types). Not that this is justification alone, but should be additionally considered.
> 
> For reason (1), I want to change it. For reason (2), I want to keep it as-is.

If i want the least restrictive (one that doesn't even validate it's existence), I would probably call it a day by just annotating as `Path` without any validators. There's not much reason to use `validators.Path()` (without args) over simply `foo: Path`

**Comment by Ravencentric** [comment]
On a side note, might be useful to bring click's `resolve_path=False` to cyclopt's

**Comment by BrianPugh** [comment]
For now, I'm going to leave the `Path` validator as-is. I agree with your reasoning, but I think the consistency (default should be least restrictive) should trump the terser syntax. That said, I think it's a bit of a moot point if you use the newly annotated types (I should have a PR in a few hours; i need to add documentation and I need to step out for a little bit).

> On a side note, might be useful to bring click's resolve_path=False to cyclopt's

Adding in `resolve_path` is a tiny bit more complicated. Since it modifies data, it's actually a `converter` rather than a `validator`. So I cannot explicitly add this to cyclopts validators. However, it can be easily DIY'd:

```
my_path: Annotated[path, Parameter(converter=lambda _, path: path.resolve(), validator=validators.Path(exists=True))]
```

I'll also add "Resolved" variants to the path types, like:

```
ResolvedPath = Annotated[path, Parameter(converter=lambda _, path: path.resolve(), validator=validators.Path(exists=True))]
# (and all the File/Directory definitions)
```

**Comment by Ravencentric** [comment]
Okay, I understand. Rest of it sounds good! Thank you!

**Comment by BrianPugh** [comment]
closing with the release of v2. We can reopen this issue, or open a new one, should the need arise.
