### ISSUE TITLE
support for union of None like Optional

### ISSUE THREAD

**Issue by samsja** [BrianPugh/cyclopts#77]
Hey, thanks for the great lib.

I think that currently  `Optional[int]` is supported but not `int | None` which should be equivalent.

Would it be possible to support it ?

thanks in advance

**Comment by BrianPugh** [comment]
Thanks for the bug report! Fixing now. I mostly code in python3.8 syntax (until it reaches EOL), so I didn't notice this issue.

The problem at heart is basically described in https://github.com/python/cpython/issues/105499

**Comment by BrianPugh** [comment]
Should be fixed in v2.1.1

**Comment by samsja** [comment]
Thanks for the ultra quick fix ! Just updated to the latest version and it is working.

> The problem at heart is basically described in https://github.com/python/cpython/issues/105499

okay this is really weird  problem that Union and | don't have the same behavior, very counterintuitive but good to know :thinking:
