### ISSUE TITLE
App() name parameter type hint adjustment

### ISSUE THREAD

**Issue by Skyler-Altol** [BrianPugh/cyclopts#78]
While doing some development testing, PyCharm has flagged the following type error:

![image](https://github.com/BrianPugh/cyclopts/assets/13567892/7ac925d7-9b5c-429a-9a71-560bcac7016a)

Per the examples in cyclopts' docs, this should work without errors. Inspecting the code inside App yields a type hint that is expecting a Tuple from the get go which is not what would initially be passed into that parameter (but would be accurate after the conversion function has run).

Current code:
`_name: Optional[Tuple[str, ...]] = field(default=None, alias="name", converter=optional_to_tuple_converter)`

Possible fix:
`_name: Optional[Union[str, Tuple[str, ...]]] = field(default=None, alias="name", converter=optional_to_tuple_converter)`

**Comment by BrianPugh** [comment]
I'll have a fix in soon, mypy#3004 strikes again.

**Comment by BrianPugh** [comment]
should be fixed in v2.1.1
